version: '3'

services:
  web-proxy:
    image: "traefik:v2.2.1"
    networks:
      solid:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/traefik/acme:rw,Z
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    privileged: true
    tty: true
    depends_on:
      - dockersocket
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=http://dockersocket:2375"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-main"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web-main.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Read: https://docs.traefik.io/https/acme/
      - "--certificatesresolvers.letsencrypt.acme.email=jase@perfectmypodcast.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # Access Traefik Dashboard: DO NOT ENABLE ON PRODUCTION
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Access with http://<Server IP ADDRESS>:8080/dashboard/ <- trailing backslash is important

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      solid:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

  solid:
    image: solidproject/community-server:latest
    command: -b https://${SOLID_DOMAIN}  -c ./config/default.json
    volumes:
      - /Solid:/data
    env_file:
      - .env
    depends_on:
      - web-proxy
    networks:
      - solid
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solid.rule=Host(`$SOLID_DOMAIN`)"
      - "traefik.http.routers.solid.entrypoints=web-main"
      - "traefik.http.routers.solid.service=solid"
      - "traefik.http.routers.solid.tls=true"
      - "traefik.http.routers.solid.tls.certresolver=letsencrypt"
      - "traefik.http.services.solid.loadbalancer.server.port=3000"

networks:
  solid:
    #  docker run --rm -v /Solid:/data -p 3000:3000 -it solidproject/community-server:latest                                             

volumes:
  acme:
